version: '3.9'

services:
  learning:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8008"
          
    ports: 
      - 8008:8008
    volumes:
      - ./learning:/learning
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devserver
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db
  

  db:
    image: postgres:13-alpine  
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_NAME=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_HOST_AUTH_METHOD=trust

    


